# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # schedule:
  #   - cron: "0 * * * *"
  push:

jobs:
  build-run-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build & Run
        run: |
          npm install -g yarn
          yarn
          yarn build
          yarn start

      - name: Commit files
        run: |
          git config --local user.email "wataru.oguchi.0to1@gmail.com"
          git config --local user.name "Wataru Bot"
          echo "::set-env name=has_new_commit::0"
          git status | grep modified && git add src/.json && git commit -v -m "[Bot] GitHub Actions - auto run" && echo "::set-env name=has_new_commit::1" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Netlify Build Hook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e8a813d1d2998dc6c47107f
        if: env.has_new_commit == 1
